In [216]:
import pandas as pd

In [217]:
f_peaks = pd.read_excel('data/female_peaks.xlsx')
f_weights = pd.read_excel('data/female_weights.xlsx')

m_peaks = pd.read_excel('data/male_peaks.xlsx')
m_weights = pd.read_excel('data/male_weights.xlsx')

In [218]:
## The first step in determining the concentrations of chemical compounds in the spider's cuticle is to calculate the masses of 
## these compounds in the analytical sample (extract), knowing that the mass of octadecane (internal standard) is 0.01 mg.

In [219]:
internal_standard_areas = f_peaks.loc[f_peaks['Name of the chemical compound'] == 'octadecane (internal standard)', 
                                      ['FEMALE 1', 'FEMALE 2', 'FEMALE 3']].values[0]
extracts_f = pd.DataFrame()

for i, female in enumerate(['FEMALE 1', 'FEMALE 2', 'FEMALE 3']):
    extracts_f[f'extract {female} (µg)'] = f_peaks[female] * (0.01 / internal_standard_areas[i]) * 1000

extracts_f['Name of the chemical compound'] = f_peaks['Name of the chemical compound']
extracts_f = extracts_f[['Name of the chemical compound'] + [col for col in extracts_f.columns if col != 'Name of the chemical compound']]

extracts_f = extracts_f[extracts_f['Name of the chemical compound'] != 'octadecane (internal standard)']
extracts_f = extracts_f.reset_index(drop=True)

In [220]:
extracts_f

,Name of the chemical compound,extract FEMALE 1 (µg),extract FEMALE 2 (µg),extract FEMALE 3 (µg)
0,lactic acid,0.026787,0.056283,0.175792
1,palmitic acid,0.475539,0.354584,0.577545
2,octadecanol,0.022978,0.019039,0.064059
3,linoleic acid,0.078700,0.134404,0.161834
4,oleic acid,0.117433,0.215801,0.245870
5,stearic acid,0.970570,0.823727,1.182100
6,tricosan,0.034627,0.428444,0.205979
7,18-methylnonadecanol,0.094851,0.025093,0.164457
8,hexacosan,0.163607,0.307064,0.366912
9,alcohol 1 (unidentified),0.342713,0.346869,0.437115
10,2-methylpentacosan,0.414199,0.212713,0.602695
11,methyl ether 1 (unidentified),0.185316,0.166889,0.310890
12,heptacosan,0.206129,0.140024,0.163598
13,methyl ether 2 (unidentified),0.494522,0.183018,0.586156

In [221]:
extracts_f.to_excel('data/female_extracts.xlsx')

In [222]:
internal_standard_areas = m_peaks.loc[m_peaks['Name of the chemical compound'] == 'octadecane (internal standard)', 
                                      ['MALE 1', 'MALE 2', 'MALE 3', 'MALE 4']].values[0]
extracts_m = pd.DataFrame()

for i, male in enumerate(['MALE 1', 'MALE 2', 'MALE 3', 'MALE 4']):
    extracts_m[f'extract {male} (µg)'] = m_peaks[male] * (0.01 / internal_standard_areas[i]) * 1000

extracts_m['Name of the chemical compound'] = m_peaks['Name of the chemical compound']
extracts_m = extracts_m[['Name of the chemical compound'] + [col for col in extracts_m.columns if col != 'Name of the chemical compound']]

extracts_m = extracts_m[extracts_m['Name of the chemical compound'] != 'octadecane (internal standard)']
extracts_m = extracts_m.reset_index(drop=True)

In [223]:
extracts_m

,Name of the chemical compound,extract MALE 1 (µg),extract MALE 2 (µg),extract MALE 3 (µg),extract MALE 4 (µg)
0,lactic acid,0.132040,0.123942,0.087817,0.083643
1,glycerol,0.078628,0.101136,0.118677,0.080679
2,myristic acid,0.054197,0.015712,0.024775,0.022456
3,palmitic acid,1.755146,0.925809,0.822149,0.801576
4,linoleic acid,0.545231,0.409174,0.210544,0.595255
5,oleic acid,0.355891,0.291575,0.189793,0.331723
6,stearic acid,1.851905,1.228618,1.045607,1.148553
7,methyl ether 3 (unidentified),0.772018,0.545009,0.636330,0.891731
8,methyl ether 4 (unidentified),1.921992,2.069673,2.664499,4.864574
9,methyl ether 5 (unidentified),0.149503,0.217092,0.177377,0.346512
10,methyl ether 6 (unidentified),0.318941,0.338009,0.376508,0.655757
11,methyl ether 7 (unidentified),1.554645,1.945503,1.687826,2.746437
12,methyl ether 8 (unidentified),0.147455,0.325920,0.224469,0.277729
13,methyl ether 9 (unidentified),0.203473,0.625533,0.303982,0.646736
14,cholesterol,0.315716,0.490091,0.301554,0.479445
15,β-sitosterol,0.092637,0.114649,0.039863,0.149052

In [224]:
extracts_m.to_excel('data/male_extracts.xlsx')

In [225]:
## The next step is to convert the masses of the chemical compounds in the extract to concentrations (per gram of spider), 
## using the known weights of the spiders used in the study.

In [226]:
weights_f = f_weights.loc[0, ['FEMALE 1', 'FEMALE 2', 'FEMALE 3']].astype(float).values

print("Weights:", weights_f)

concentrations_female = extracts_f[['Name of the chemical compound']].copy()

for i, female in enumerate(['FEMALE 1', 'FEMALE 2', 'FEMALE 3']):
    extract_values = extracts_f[f'extract {female} (µg)'].astype(float)  
    weight = weights_f[i] 
    
    concentrations_female[f'concentrations {female} (µg/g)'] = extract_values / weight

concentrations_female.iloc[:, 1:] = concentrations_female.iloc[:, 1:].round(2)

Weights: [0.0259 0.0409 0.0337]

In [227]:
concentrations_female

,Name of the chemical compound,concentrations FEMALE 1 (µg/g),concentrations FEMALE 2 (µg/g),concentrations FEMALE 3 (µg/g)
0,lactic acid,1.03,1.38,5.22
1,palmitic acid,18.36,8.67,17.14
2,octadecanol,0.89,0.47,1.90
3,linoleic acid,3.04,3.29,4.80
4,oleic acid,4.53,5.28,7.30
5,stearic acid,37.47,20.14,35.08
6,tricosan,1.34,10.48,6.11
7,18-methylnonadecanol,3.66,0.61,4.88
8,hexacosan,6.32,7.51,10.89
9,alcohol 1 (unidentified),13.23,8.48,12.97
10,2-methylpentacosan,15.99,5.20,17.88
11,methyl ether 1 (unidentified),7.16,4.08,9.23
12,heptacosan,7.96,3.42,4.85
13,methyl ether 2 (unidentified),19.09,4.47,17.39

In [228]:
concentrations_female.to_excel('data/female_concentrations.xlsx')

In [229]:
weights_m = m_weights.loc[0, ['MALE 1', 'MALE 2', 'MALE 3', 'MALE 4']].astype(float).values

print("Weights:", weights_m)

concentrations_male = extracts_m[['Name of the chemical compound']].copy()

for i, male in enumerate(['MALE 1', 'MALE 2', 'MALE 3', 'MALE 4']):
    extract_values = extracts_m[f'extract {male} (µg)'].astype(float)  
    weight = weights_m[i] 
    
    concentrations_male[f'concentrations {male} (µg/g)'] = extract_values / weight

concentrations_male.iloc[:, 1:] = concentrations_male.iloc[:, 1:].round(2)

Weights: [0.011  0.0141 0.0205 0.0179]

In [230]:
concentrations_male

,Name of the chemical compound,concentrations MALE 1 (µg/g),concentrations MALE 2 (µg/g),concentrations MALE 3 (µg/g),concentrations MALE 4 (µg/g)
0,lactic acid,12.00,8.79,4.28,4.67
1,glycerol,7.15,7.17,5.79,4.51
2,myristic acid,4.93,1.11,1.21,1.25
3,palmitic acid,159.56,65.66,40.10,44.78
4,linoleic acid,49.57,29.02,10.27,33.25
5,oleic acid,32.35,20.68,9.26,18.53
6,stearic acid,168.35,87.14,51.01,64.16
7,methyl ether 3 (unidentified),70.18,38.65,31.04,49.82
8,methyl ether 4 (unidentified),174.73,146.79,129.98,271.76
9,methyl ether 5 (unidentified),13.59,15.40,8.65,19.36
10,methyl ether 6 (unidentified),28.99,23.97,18.37,36.63
11,methyl ether 7 (unidentified),141.33,137.98,82.33,153.43
12,methyl ether 8 (unidentified),13.40,23.11,10.95,15.52
13,methyl ether 9 (unidentified),18.50,44.36,14.83,36.13
14,cholesterol,28.70,34.76,14.71,26.78
15,β-sitosterol,8.42,8.13,1.94,8.33

In [231]:
concentrations_male.to_excel('data/male_concentrations.xlsx')